### ISSUE TITLE
Do the new images work?

### ISSUE THREAD

**Issue by dannysemi** [runpod-workers/worker-vllm#51] opened 2024-02-23 06:00 UTC
I based my custom worker on the vllm-base image `base-0.3.0-cuda12.1.0` but if I try to run it with multiple gpus I get this error:

```
"ImportError: NCCLBackend is not available. Please install cupy."
```

It works fine if I'm only using one gpu. I saw this comment on the sls-worker repo at [Dockerfile](https://github.com/runpod/vllm-fork-for-sls-worker/blob/main/Dockerfile#L78):
```
# We used base cuda image because pytorch installs its own cuda libraries.
# However cupy depends on cuda libraries so we had to switch to the runtime image
# In the future it would be nice to get a container with pytorch and cuda without duplicating cuda
FROM nvidia/cuda:12.1.0-runtime-ubuntu22.04 AS vllm-base
```
Was this Dockerfile used to create the base image?

I can see cupy listed in the [requirements.txt](https://github.com/runpod/vllm-fork-for-sls-worker/blob/bfd21437e32a79a61ea31b6b88377f2338761dd8/requirements.txt#L15) too.

**Comment by alpayariyak** [comment] 2024-02-23 06:18
Hey, could you try adding the installation of cupy with the specified version into the worker Dockerfile?

**Comment by dannysemi** [comment] 2024-02-23 06:24
> Hey, could you try adding the installation of cupy with the specified version into the worker Dockerfile?

Oh that makes sense. I'll try that now.

**Comment by dannysemi** [comment] 2024-02-23 06:35
I got the same error. I must be doing something wrong.

**Comment by alpayariyak** [comment] 2024-02-23 06:37
I haven't tested multi-gpu yet, will be doing working on fixing this later today

**Comment by alpayariyak** [comment] 2024-02-23 06:54
Seems like the quickest way to fix this, if following in vLLM's steps, will be to use the runtime image instead of base like they did in the snippet you shared, but the issue is that it would make the container 1.5GB heavier

**Comment by dannysemi** [comment] 2024-02-23 07:05
Not ideal, but it looks like they didn't have a better solution either.

Also, they added lora support I guess. https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/openai/serving_chat.py#L25

I'm just ignoring it for now with this change: https://github.com/dannysemi/worker-vllm/commit/d90b012a5f7ad78c483ccad7718c4d54c5931d3f#diff-865c0134cc71b80102811a3e1216d5dad097594d0a4cabcb4dfc077d925af689R200

I didn't see a change for that here.

**Comment by alpayariyak** [comment] 2024-02-23 07:12
If you're interested, the `openai-sse-branch` (soon to be released as 0.3.0) has OpenAI compatibility, support for Gemma, general improvements and new features - the docs are up-to-date to get you started. You'll have to enforce eager there too until I fix the multi-gpu issue, but it's available as an env variable.

**Comment by dannysemi** [comment] 2024-02-23 07:18
Awesome! Thanks

**Comment by dannysemi** [comment] 2024-02-23 08:07
> If you're interested, the `openai-sse-output` branch (soon to be released as 0.3.0) has OpenAI compatibility, support for Gemma, general improvements and new features - the docs are up-to-date to get you started. You'll have to enforce eager there too until I fix the multi-gpu issue, but it's available as an env variable.

I just tried out the new OpenAI compatibility and it works great. Good job!

**Comment by alpayariyak** [comment] 2024-02-23 08:58
Thank you, great to hear that! :) 

Let me know if you run into any issues or have feature requests

**Comment by alpayariyak** [comment] 2024-02-24 03:42
Fixed Multi-GPU in 0.3.0 release :)

**Closed by alpayariyak** 2024-02-24 03:42 UTC

**Comment by dannysemi** [comment] 2024-02-24 04:27
Thanks again. If I was already using this image in a region, will it pull the fixed image without the version being bumped?

**Comment by alpayariyak** [comment] 2024-02-24 05:25
Only if the workers are deleted/restarted
